services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force || true
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
    autoDeploy: true
